// Nomes legíveis das tabelas e colunas gravadas pela auditoria da API (camelCase ou snake_case).
export const ENTITY_LABELS: Record<string, string> = {
  suppliers: 'Fornecedor',
  supplier: 'Fornecedor',
  users: 'Usuário',
  user: 'Usuário',
  products: 'Produto',
  product: 'Produto',
  batch: 'Lote',
  batches: 'Lote',
  chain: 'Etapa',
  certification: 'Certificação',
  report: 'Relatório',
  transport: 'Transporte',
  address: 'Endereço',
  carbon_emission: 'Emissão',
};

export const FIELD_LABELS: Record<string, string> = {
  name: 'Nome',
  cnpj: 'CNPJ',
  email: 'Email',
  role: 'Perfil',
  status: 'Status',
  quantity: 'Quantidade',
  producedAt: 'Data de produção',
  produced_at: 'Data de produção',
  certification: 'Certificação',
  issuingBody: 'Órgão emissor',
  issuing_body: 'Órgão emissor',
  phone: 'Telefone',
  description: 'Descrição',
  stageType: 'Etapa',
  stage_type: 'Etapa',
  started_at: 'Início',
  ended_at: 'Término',
  expires_at: 'Validade',
  issued_at: 'Emissão',
  created_at: 'Criado em',
  registered_at: 'Cadastro',
  address_id: 'Endereço (ID)',
  supplier_id: 'Fornecedor (ID)',
  product_id: 'Produto (ID)',
  responsible_user_id: 'Responsável (ID)',
  batch_id: 'Lote (ID)',
  chain_id: 'Etapa (ID)',
};
