import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { SuppliersService } from '../index.service';
@Component({ selector:'app-suppliers-form', imports:[ReactiveFormsModule, RouterLink], templateUrl:'./index.component.html', changeDetection:ChangeDetectionStrategy.OnPush })
export class SupplierFormComponent {
  private readonly fb=inject(FormBuilder); private readonly service=inject(SuppliersService); private readonly route=inject(ActivatedRoute); private readonly router=inject(Router);
  readonly editing=signal(!!this.route.snapshot.paramMap.get('id') || this.route.snapshot.routeConfig?.path === 'suppliers/me'); readonly saving=signal(false); readonly error=signal('');
  readonly form=this.fb.group({ name: ['', [Validators.required]], cnpj: ['', [Validators.required]], phone: ['', [Validators.required]], street: ['', [Validators.required]], number: ['', [Validators.required]], neighborhood: ['', [Validators.required]], complement: ['', []], zipCode: ['', [Validators.required]], city: ['', [Validators.required]], state: ['', [Validators.required]] });
  constructor() { const id = this.route.snapshot.paramMap.get('id') ?? (this.route.snapshot.routeConfig?.path === 'suppliers/me' ? sessionStorage.getItem('supplierId') : null); if (id) this.service.get(Number(id)).subscribe({ next: (supplier) => this.form.patchValue({ name: supplier.name, cnpj: supplier.cnpj, phone: supplier.phone, street: supplier.address.street, number: supplier.address.number, neighborhood: supplier.address.neighborhood, complement: supplier.address.complement, zipCode: supplier.address.zipCode, city: supplier.address.city, state: supplier.address.state }), error: () => this.error.set('Não foi possível carregar o fornecedor.') }); else if (this.route.snapshot.routeConfig?.path === 'suppliers/me') this.error.set('Não foi possível identificar o fornecedor desta sessão.'); }
  private data(): any { const v = this.form.getRawValue(); return { name:v.name, cnpj:v.cnpj, phone:v.phone, address:{ street:v.street, number:v.number, neighborhood:v.neighborhood, complement:v.complement, zipCode:v.zipCode, city:v.city, state:v.state } }; }
  submit(): void { if(this.form.invalid){this.form.markAllAsTouched();return;} this.saving.set(true); const supplierId = this.route.snapshot.paramMap.get('id') ?? sessionStorage.getItem('supplierId'); (this.editing() ? this.service.update(Number(supplierId), this.data()) : this.service.create(this.data())).subscribe({next:()=>{this.saving.set(false);this.router.navigate(['/suppliers']);},error:()=>{this.saving.set(false);this.error.set('Não foi possível salvar. Confira os dados e tente novamente.');}}); }
}
